# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hangman.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelWord = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelWord.setFont(font)
        self.labelWord.setAlignment(QtCore.Qt.AlignCenter)
        self.labelWord.setObjectName("labelWord")
        self.verticalLayout.addWidget(self.labelWord)
        self.lineEditGuess = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEditGuess.setFont(font)
        self.lineEditGuess.setMaxLength(1)
        self.lineEditGuess.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditGuess.setObjectName("lineEditGuess")
        self.verticalLayout.addWidget(self.lineEditGuess)
        self.btnSubmit = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnSubmit.setFont(font)
        self.btnSubmit.setObjectName("btnSubmit")
        self.verticalLayout.addWidget(self.btnSubmit)
        self.labelInfo = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelInfo.setFont(font)
        self.labelInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelInfo.setObjectName("labelInfo")
        self.verticalLayout.addWidget(self.labelInfo)
        self.canvasWidget = QtWidgets.QWidget(self.centralwidget)
        self.canvasWidget.setMinimumSize(QtCore.QSize(400, 250))
        self.canvasWidget.setObjectName("canvasWidget")
        self.verticalLayout.addWidget(self.canvasWidget)
        self.btnPlayAgain = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnPlayAgain.setFont(font)
        self.btnPlayAgain.setObjectName("btnPlayAgain")
        self.verticalLayout.addWidget(self.btnPlayAgain)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hangman Game"))
        self.labelWord.setText(_translate("MainWindow", "_ _ _ _ _"))
        self.btnSubmit.setText(_translate("MainWindow", "Submit Guess"))
        self.labelInfo.setText(_translate("MainWindow", "Incorrect guesses will be shown here."))
        self.btnPlayAgain.setText(_translate("MainWindow", "Play Again"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
